# Generated by Django 6.0.7 on 2026-07-16 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('stock_securite', models.IntegerField(default=5)),
                ('stock_min', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.categorie')),
            ],
        ),
    ]
