# Generated by Django 5.2.8 on 2026-07-17 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignevente',
            old_name='prix_achat',
            new_name='prix_achat_unitaire',
        ),
        migrations.RenameField(
            model_name='lignevente',
            old_name='prix_vente',
            new_name='prix_vente_unitaire',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='total',
        ),
        migrations.AddField(
            model_name='vente',
            name='facture_pdf_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='marge_totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
