# Generated by Django 5.2.8 on 2026-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('soldee', models.BooleanField(default=False)),
            ],
        ),
    ]
