# Generated by Django 5.2.8 on 2026-07-17 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
        ('fournisseurs', '0003_alter_fournisseur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='fournisseurs.fournisseur'),
        ),
    ]
